export const PROJECT_ARCHIVE = 'PROJECT_ARCHIVE';
export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECTS_FETCH_ERROR = 'PROJECTS_FETCH_ERROR';
export const PROJECTS_LOAD = 'PROJECTS_LOAD';
export const PROJECT_LOAD = 'PROJECT_LOAD';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT;'